---
control:
  hosts:
    ubuntu-c:
      ansible_connection: local

ubuntus:
  hosts:
    ubuntu1:
    ubuntu2:
    ubuntu3:
  vars:
    ansible_become: true
    ansible_become_pass: password

linux:
  children:
    control:
    ubuntus:
...
