---
control:
  hosts:
    ubuntu-c:
      ansible_connection: local

centos:
  hosts:
    centos1:
  vars:
    ansible_become: true
    ansible_become_pass: password

ubuntus:
  hosts:
    ubuntu1:
    ubuntu2:
  vars:
    ansible_become: true
    ansible_become_pass: password

linux:
  children:
    centos:
    ubuntus:
...
